# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimestampData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TimestampData.proto',
  package='pysub',
  serialized_pb='\n\x13TimestampData.proto\x12\x05pysub\"=\n\rTimestampData\x12\x11\n\tTimestamp\x18\x01 \x02(\x03\x12\x0b\n\x03Key\x18\x02 \x02(\t\x12\x0c\n\x04\x44\x61ta\x18\x03 \x02(\x01')




_TIMESTAMPDATA = _descriptor.Descriptor(
  name='TimestampData',
  full_name='pysub.TimestampData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='pysub.TimestampData.Timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Key', full_name='pysub.TimestampData.Key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='pysub.TimestampData.Data', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['TimestampData'] = _TIMESTAMPDATA

class TimestampData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMESTAMPDATA

  # @@protoc_insertion_point(class_scope:pysub.TimestampData)


# @@protoc_insertion_point(module_scope)
